import { Injectable, signal, computed } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../environments/environment';
import { Address, Brand, CartItem, Category, Order, Product, User } from '../models';
@Injectable({providedIn:'root'})
export class StoreService{
 categories:Category[]=[{id:1,name:'OTC Medicines',slug:'otc-medicines',icon:'💊',description:'Daily pharmacy essentials'},{id:2,name:'Prescription Medicines',slug:'prescription-medicines',icon:'🧾',description:'Doctor prescribed medicines'},{id:3,name:'Baby Care',slug:'baby-care',icon:'🧴',description:'Lotion, wipes and infant care'},{id:4,name:'Milk Powder',slug:'milk-powder',icon:'🍼',description:'Infant formula and nutrition'},{id:5,name:'Vitamins',slug:'vitamins',icon:'🍊',description:'Vitamin wellness products'},{id:6,name:'Supplements',slug:'supplements',icon:'🌿',description:'Health supplements'},{id:7,name:'Protein Products',slug:'protein-products',icon:'💪',description:'Protein powder and bars'},{id:8,name:'Healthcare Devices',slug:'healthcare-devices',icon:'🩺',description:'Health monitoring devices'},{id:9,name:'Personal Care',slug:'personal-care',icon:'🧼',description:'Hygiene products'},{id:10,name:'Beauty Products',slug:'beauty-products',icon:'✨',description:'Skin essentials'}];
 brands:Brand[]=['Nestle','Abbott','PediaSure','Johnson & Johnson','Himalaya','Pampers','Dettol','Aptamil','Ensure','Dabur','Cipla','Sun Pharma'].map((name,i)=>({id:i+1,name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}));
 products:Product[]=this.makeProducts();
 user=signal<User|null>(JSON.parse(localStorage.getItem('pharmacy_user')||'null'));
 cart=signal<CartItem[]>(JSON.parse(localStorage.getItem('pharmacy_cart')||'[]'));
 wishlist=signal<number[]>(JSON.parse(localStorage.getItem('pharmacy_wishlist')||'[]'));
 compare=signal<number[]>(JSON.parse(localStorage.getItem('pharmacy_compare')||'[]'));
 addresses=signal<Address[]>(JSON.parse(localStorage.getItem('pharmacy_addresses')||'[]'));
 orders=signal<Order[]>(JSON.parse(localStorage.getItem('pharmacy_orders')||'[]'));
 cartCount=computed(()=>this.cart().reduce((s,i)=>s+i.quantity,0)); cartTotal=computed(()=>this.cart().reduce((s,i)=>s+i.product.price*i.quantity,0));
 constructor(private http: HttpClient){ this.loadApiData(); }
 loadApiData(){
   this.http.get<Category[]>(`${environment.apiUrl}/categories`).subscribe({next:v=>{if(v?.length)this.categories=v.map((c:any)=>({id:c.id,name:c.name||c.category_name,slug:c.slug,icon:c.icon||'💊',description:c.description||''}));},error:()=>{}});
   this.http.get<Brand[]>(`${environment.apiUrl}/brands`).subscribe({next:v=>{if(v?.length)this.brands=v.map((b:any)=>({id:b.id,name:b.name||b.brand_name,slug:b.slug}));},error:()=>{}});
   this.http.get<Product[]>(`${environment.apiUrl}/products`).subscribe({next:v=>{if(v?.length)this.products=v;},error:()=>{}});
 }
 makeProducts(){const names=['Paracetamol 500mg','Dolo 650','Cetirizine','Vitamin C Sugarless','Vitamin D3 Capsule','Omega 3 Fish Oil','Multivitamin Complete','Whey Protein Chocolate','Protein Isolate Vanilla','Nestle NAN Optipro','Nestle Lactogen','Aptamil Gold Infant Formula','Similac Advance','PediaSure Vanilla','Johnson Baby Lotion','Johnson Baby Oil','Baby Shampoo Mild','Baby Wipes Pack','Himalaya Baby Cream','Dettol Hand Wash','Digital Thermometer','BP Monitor Digital','Pulse Oximeter','Face Wash Gentle','Sunscreen SPF 50','Herbal Liver Detox','Cough Syrup Honey','Antacid Gel','Pain Relief Spray','Calcium Tablets'];let list:Product[]=[];for(let i=1;i<=1000;i++){const c=this.categories[(i-1)%this.categories.length],b=this.brands[(i-1)%this.brands.length],n=names[(i-1)%names.length]+' '+i,price=+(99+(i%650)+(i%9)*3.5).toFixed(2),mrp=+(price+20+(i%160)).toFixed(2);list.push({id:i,name:n,slug:n.toLowerCase().replace(/[^a-z0-9]+/g,'-'),sku:'MED-'+String(i).padStart(5,'0'),category:c.name,categorySlug:c.slug,brand:b.name,brandSlug:b.slug,mrp,price,stock:20+(i%220),rating:3.5+((i%15)/10),reviews:5+(i%340),image:c.icon,description:'Quality pharmacy product for family healthcare and wellness. Includes information for use, safety, stock and delivery eligibility.',ingredients:'Approved ingredients as per product category. Read product label before use.',dosage:i%3===0?'Use only as directed by physician.':'Use as mentioned on product label.',warnings:i%4===0?'Prescription may be required. Keep away from children.':'Store in a cool and dry place.',featured:i<=48,prescription:c.slug==='prescription-medicines'});}return list;}
 query(o:any={}){let p=[...this.products]; if(o.q)p=p.filter(x=>(x.name+x.category+x.brand).toLowerCase().includes(String(o.q).toLowerCase())); if(o.category)p=p.filter(x=>x.categorySlug===o.category); if(o.brand)p=p.filter(x=>x.brandSlug===o.brand); if(o.prescription)p=p.filter(x=>x.prescription); if(o.min)p=p.filter(x=>x.price>=+o.min); if(o.max)p=p.filter(x=>x.price<=+o.max); if(o.sort==='price-low')p.sort((a,b)=>a.price-b.price); if(o.sort==='price-high')p.sort((a,b)=>b.price-a.price); if(o.sort==='rating')p.sort((a,b)=>b.rating-a.rating); if(o.sort==='new')p.sort((a,b)=>b.id-a.id); return p;}
 product(id:number){return this.products.find(p=>p.id===id)} related(p:Product){return this.products.filter(x=>x.id!==p.id&&(x.categorySlug===p.categorySlug||x.brandSlug===p.brandSlug)).slice(0,8)}
 addCart(p:Product,q=1){const items=[...this.cart()];const f=items.find(i=>i.product.id===p.id);f?f.quantity+=q:items.push({product:p,quantity:q});this.saveCart(items)} updateCart(id:number,q:number){this.saveCart(this.cart().map(i=>i.product.id===id?{...i,quantity:q}:i).filter(i=>i.quantity>0))} removeCart(id:number){this.saveCart(this.cart().filter(i=>i.product.id!==id))} clearCart(){this.saveCart([])} saveCart(v:CartItem[]){this.cart.set(v);localStorage.setItem('pharmacy_cart',JSON.stringify(v))}
 toggleWishlist(id:number){const s=new Set(this.wishlist());s.has(id)?s.delete(id):s.add(id);const v=[...s];this.wishlist.set(v);localStorage.setItem('pharmacy_wishlist',JSON.stringify(v))} toggleCompare(id:number){const arr=this.compare();const v=arr.includes(id)?arr.filter(x=>x!==id):[...arr,id].slice(-4);this.compare.set(v);localStorage.setItem('pharmacy_compare',JSON.stringify(v))}
 login(email:string){const u={id:1,name:email.includes('admin')?'Admin':'Customer',email,role:email.includes('admin')?'ADMIN':'CUSTOMER'} as User;this.user.set(u);localStorage.setItem('pharmacy_user',JSON.stringify(u));localStorage.setItem('pharmacy_token','demo-token')} logout(){this.user.set(null);localStorage.removeItem('pharmacy_user');localStorage.removeItem('pharmacy_token')}
 saveAddress(a:Address){const list=[...this.addresses()];if(!a.id)a.id=Date.now();const i=list.findIndex(x=>x.id===a.id);i>=0?list[i]=a:list.push(a);this.addresses.set(list);localStorage.setItem('pharmacy_addresses',JSON.stringify(list))}
 placeOrder(method:string,address?:Address){const o:Order={id:Date.now(),number:'ORD-'+Date.now(),date:new Date().toISOString(),status:'Processing',paymentStatus:method==='Cash on Delivery'?'Pending':'Paid',paymentMethod:method,total:this.cartTotal(),items:this.cart(),address,tracking:[{label:'Order placed',done:true,date:new Date().toISOString()},{label:'Packed',done:false},{label:'Shipped',done:false},{label:'Delivered',done:false}]};const list=[o,...this.orders()];this.orders.set(list);localStorage.setItem('pharmacy_orders',JSON.stringify(list));this.clearCart();return o;}
}
